# This Makefile is meant for local builds of the container images built for
# the Openshift Sandboxed Containers operator.
# It relies on Dockerfiles and settings specific to our Konflux build pipelines,
# and allows to locally build images that are as close as possible to what our
# CI will produce.
#
# You can run "make -f Makefile.osc [image]" to build a specific image.
# You can run "make -f Makefile.osc help" to get a list of all available images.
#
# You can use the environmnet variable "HERMETIC_BUILD=1" to build images
# in hermetic mode, which will run "hermeto" as part of the build to retrieve
# all dependencies.
# e.g: "HERMETIC_BUILD=1 make -f Makefile.osc osc-podvm-payload"
#
# You can pass extra arguments to "buildah build" with "BUILD_PARAMS".
# e.g: "BUILD_PARAMS=--no-cache make -f Makefile.osc osc-podvm-payload"
#
# Builds use "buildah" to benefit from parallel multi-stage builds (--jobs).
# You can control the number of parallel jobs with "BUILD_JOBS".
# e.g: "BUILD_JOBS=4 make -f Makefile.osc osc-podvm-payload"
# By default, it uses the number of available CPUs.
#
# For multi-stage Dockerfiles (e.g. osc-podvm-payload), you can build a single
# stage using "--target" via BUILD_PARAMS:
# e.g: "BUILD_PARAMS='--target build_kata_agent' make -f Makefile.osc osc-podvm-payload"
#
# Available stages for osc-podvm-payload:
#   go_builder                    - Base Go build environment
#   build_agent_proto_forwarder   - agent-protocol-forwarder (Go)
#   build_process_user_data       - process-user-data (Go)
#   rust_builder                  - Base Rust build environment
#   build_kata_agent              - kata-agent (Rust)
#   build_attestation_agent       - attestation-agent (Rust)
#   build_api_server_rest         - api-server-rest (Rust)
#   build_confidential_data_hub   - confidential-data-hub (Rust)
#   pause_builder                 - pause container bundle

#
# Note about Subscription:
# When images need to install packages from Red Hat repositories, the build
# process will expect to find a valid subscription on the host system.
# For a hermetic build, the subscription must be available to the Hermeto process.
#
# For a non-hermetic build, the subscription must be available to buildah.
#
# This Makefile assumes that you have a "activation-key" folder in the current
# directory containing the subscription files as "org" and "activation-key".
#
# For a non-hermetic build, you also need to edit the Dockerfile to uncomment
# the lines invoking subscription-manager.

HERMETIC_BUILD ?= 0

BUILD_JOBS ?= $(shell nproc)
BUILD_PARAMS ?=

HERMETO = podman run --rm -ti -v "$(BDIR):$(BDIR):z" -v "$(BDIR)/activation-key:/activation-key:Z" -w "$(BDIR)" quay.io/redhat-user-workloads/ose-osc-tenant/osc-hermeto:latest

osc-caa: FETCH_PARAMS='[{"type": "rpm", "path": "./src/cloud-api-adaptor/"}, {"type": "gomod", "path": "./src/cloud-api-adaptor"}]'
osc-caa-webhook: FETCH_PARAMS='{"type": "gomod", "path": "./src/webhook/"}'
osc-podvm-payload: FETCH_PARAMS='[{"type": "rpm", "path": "./podvm-payload/"}, {"type": "gomod", "path": "./src/cloud-api-adaptor/"}, {"type": "cargo", "path": "./podvm-payload/kata-containers/"}, {"type": "cargo", "path": "./podvm-payload/guest-components/"}, {"type": "cargo", "path": "./podvm-payload/guest-components/attestation-agent/nvidia-attestation-sdk/nv-attestation-sdk-cpp/vendor/regorus/bindings/ffi/"}]'

osc-caa: DOCKERFILE=./src/cloud-api-adaptor/Dockerfile.openshift
osc-caa-webhook: DOCKERFILE=./src/webhook/Dockerfile
osc-podvm-payload: DOCKERFILE=./podvm-payload/Dockerfile

osc-caa: BUILD_PARAMS+=--build-arg-file .tekton/caa-build-args.env -f cloud-api-adaptor/Dockerfile.openshift
osc-caa-webhook: BUILD_PARAMS+=-f Dockerfile
osc-podvm-payload: BUILD_PARAMS+=-f podvm-payload/Dockerfile

osc-caa: BUILD_CONTEXT=./src/
osc-caa-webhook: BUILD_CONTEXT=./src/webhook/
osc-podvm-payload: BUILD_CONTEXT=.

TMPDIR ?= /tmp

osc-%: BDIR=$(TMPDIR)/build-osc-$*

define clean-build
	# There might be 444 directories
	chmod -Rf +w ${BDIR} ; rm -rf ${BDIR}
endef

ifeq ($(HERMETIC_BUILD),1)
# Use :z (shared SELinux label) instead of :Z (private) so parallel build
# stages can all access the cachi2 volume simultaneously.
BUILD_PARAMS += --network=none -v "$(BDIR)/cachi2":/cachi2:z
else
BUILD_PARAMS += --secret id=org_id,src=activation-key/org --secret id=activation_key,src=activation-key/activation-key
endif

# .PHONY doesn't work with pattern rules. Use the empty FORCE target
# workaround as documented in `info make`.
osc-%: FORCE
	# Always start from scratch
	$(clean-build)
	rsync -a . $(BDIR)
ifeq ($(HERMETIC_BUILD),1)
	${HERMETO} ${FETCH_PARAMS}

	# prefix all "RUN" commands to load hermeto env
	sed -i 's|^\(RUN\(\( --mount=[^ ]*\)*\)\) |\1 . /cachi2/cachi2.env \&\&|g' $(BDIR)/${DOCKERFILE}

	# uncomment the line that installs the proper yum repo file in Dockerfile
	sed -i 's|^#RUN rm /etc/yum.repos.d/|RUN rm /etc/yum.repos.d/|' $(BDIR)/${DOCKERFILE}
endif
	cd $(BDIR) && buildah build --jobs $(BUILD_JOBS) -t osc-$* ${BUILD_PARAMS} ${BUILD_CONTEXT}
	$(clean-build)

FORCE:

help:
	@echo "Available targets:"
	@echo "  osc-caa             - Build the Cloud API Adaptor image"
	@echo "  osc-caa-webhook     - Build the Cloud API Adaptor Webhook image"
	@echo "  osc-podvm-payload   - Build the PodVM Payload image"
	@echo ""
	@echo "You can set HERMETIC_BUILD=1 to build images in hermetic mode."
	@echo "You can set BUILD_JOBS=N to control the number of parallel build stages"
	@echo "(defaults to the number of available CPUs)."
	@echo "You can pass extra arguments to buildah build with BUILD_PARAMS,"
	@echo "e.g. BUILD_PARAMS=--no-cache make -f Makefile.osc osc-podvm-payload"
	@echo ""
	@echo "To build a single Dockerfile stage, use --target via BUILD_PARAMS:"
	@echo "e.g. BUILD_PARAMS='--target build_kata_agent' make -f Makefile.osc osc-podvm-payload"
.PHONY: help
