apiVersion: batch/v1
kind: Job
metadata:
  name: ami-create-job
  namespace: confidential-containers-system
spec:
  parallelism: 1    
  completions: 1    
  template:         
    metadata:
      name: ami-create-job
# needs hostnet for ocp
    spec:
      volumes:
      - name: shared-data
        emptyDir: {}

      initContainers:
      - name: payload
        # change
        image: quay.io/snir/podvm-binaries-rhel
        volumeMounts:
        - name: shared-data
          mountPath: /payload
        command: ["/bin/sh"]
        args: ["-c", "cp /podvm-binaries.tar.gz /payload/ && cp /pause-bundle.tar.gz /payload/"]
      containers:
      - name: ami-create-job
        image: registry.access.redhat.com/ubi8/ubi:8.7
        volumeMounts:
        - name: shared-data
          mountPath: /payload
        env:
          - name: PODVM_DISTRO
            value: rhel
          #change
          - name: INSTANCE_TYPE
            value: "t2.small"
          - name: RUST_VERSION
            value: "1.66.0"
          - name: GO_VERSION
            value: "1.19.6"
          - name: PROTOC_VERSION
            value: "3.11.4"
#          - name: IMAGE_NAME
#            value: "peer-pod-ami"
#          - name: AWS_REGION
#            value: ""
#          - name: VPC_ID
#            value: ""
#          - name: SUBNET_ID
#            value: ""
        envFrom:
        - secretRef:
            name: peer-pods-secret
        - configMapRef:
            name: peer-pods-cm
        command:
        - /bin/sh
        - -c
        - |
          yum install -y yum-utils make git
          yum-config-manager --add-repo https://rpm.releases.hashicorp.com/RHEL/hashicorp.repo
          yum -y install packer
          PATH="/usr/bin:${PATH}"
          packer plugins install github.com/hashicorp/amazon
          git clone https://github.com/bpradipt/cloud-api-adaptor.git -b podvm_binaries
          tar xvf /payload/pause-bundle.tar.gz -C cloud-api-adaptor/podvm/files
          tar xvf /payload/podvm-binaries.tar.gz -C cloud-api-adaptor/podvm/files
          export MAC=$(curl -m 30 -s --show-error http://169.254.169.254/latest/meta-data/mac)
          echo "### mac: ${MAC}"
          [[ ! "${AWS_REGION}" ]] && export AWS_REGION=$(curl -m 30 -s --show-error http://169.254.169.254/latest/meta-data/placement/region)
          echo "### region: ${AWS_REGION}"
          [[ ! "${VPC_ID}" ]] && export VPC_ID=$(curl -m 30 -s --show-error http://169.254.169.254/latest/meta-data/network/interfaces/macs/${MAC}/vpc-id)
          echo "### vpc-id: ${VPC_ID}"
          [[ ! "${SUBNET_ID}" ]] && export SUBNET_ID=$(curl -m 30 -s --show-error http://169.254.169.254/latest/meta-data/network/interfaces/macs/${MAC}/subnet-id)
          echo "### subnet-id: ${SUBNET_ID}"
          cd cloud-api-adaptor/aws/image
          LIBC=gnu make BINARIES= PAUSE_BUNDLE= image
      restartPolicy: Never
