#!/usr/bin/env bash

# Create EC2 launch template
aws ec2 create-launch-template --launch-template-name kata --version-description version1 \
  --launch-template-data "{\"NetworkInterfaces\":[{\"DeviceIndex\":0,\"AssociatePublicIpAddress\":true,\"Groups\":[\"$SEC_GROUP\"],\"SubnetId\":\"$SUBNET_ID\",\"DeleteOnTermination\":true}],\"ImageId\":\"$AMI_ID\",\"InstanceType\":\"t2.small\"}" --region $REGION

# Delete EC2 launch template
#aws ec2 delete-launch-template --launch-template-name kata --region $REGION
